Repository mixpanel/mixpanel-swift, pull requests merged in 2022-04, with the labels that each got.

#530 Allow setting server URL during initialization
  Sources/Mixpanel.swift
  Sources/MixpanelInstance.swift
Labels: bug

#537 Add Dev NPS Survey Log & semaphore.signal() in Decide
  Sources/Decide.swift
  Sources/Mixpanel.swift
  Sources/MixpanelInstance.swift
  Sources/Network.swift
Labels: bug, enhancement

#540 Add additional SDK internal tracking
  MixpanelDemo/MixpanelDemo.xcodeproj/xcshareddata/xcschemes/MixpanelDemoWatch (Notification).xcscheme
  MixpanelDemo/MixpanelDemo.xcodeproj/xcshareddata/xcschemes/MixpanelDemoWatch.xcscheme
  MixpanelDemo/MixpanelDemo/Base.lproj/LaunchScreen.storyboard
  MixpanelDemo/MixpanelDemo/Base.lproj/Main.storyboard
  MixpanelDemo/MixpanelDemo/LoginViewController.swift
  Sources/Mixpanel.swift
  Sources/MixpanelInstance.swift
  Sources/Network.swift
Labels: enhancement
